openapi: 3.0.3
info:
  title: API - OAS First Demo
  version: 1.0.0
  description: For demo purpose.
  x-logo:
    url: >-
      https://image.winudf.com/v2/image1/dHJhZGVmb3JjZS5hY2NlcmEuY29tX2ljb25fMTU3MDU2NzA0M18wNDQ/icon.png?w=170&fakeurl=1
  license: null
  contact: null
servers:
  - url: 'https://api.example.io'
paths:
  /users:
    summary: Users data
    get:
      tags: []
    put:
      tags: []
    post:
      tags: []
    delete:
      tags: []
    x-last-modified: 1605720824588
  /roadmaps:
    summary: Roadmap data
    get:
      tags: []
    post:
      tags: []
    x-last-modified: 1605721026679
components:
  schemas:
    name:
      format: ''
      pattern: ''
      enum: []
      type: string
      example: ''
      x-last-modified: 1605720918899
  securitySchemes: {}
  responses: {}
  parameters: {}
tags: []
security: []
externalDocs: null
